import {
  Activity,
  AlertTriangle,
  BookOpen,
  Bot,
  Building,
  CheckSquare,
  ClipboardCopy,
  FileText,
  Folder,
  HelpCircle,
  Key,
  Map,
  PieChart,
  Rocket,
  ShieldCheck,
  Users,
  WifiOff,
} from 'lucide-react';
import type { Section } from '@/types/userManual';

export const sections: Section[] = [
  { id: 'overview', title: 'Platform Overview', icon: BookOpen },
  { id: 'roles', title: 'User Roles', icon: Users },
  { id: 'login', title: 'First-Time Login Guide', icon: Key },
  { id: 'start-pilot', title: 'Start Pilot Workflow', icon: Rocket },
  { id: 'enterprise', title: 'Enterprise Module', icon: Building },
  { id: 'projects', title: 'Project Management', icon: Folder },
  { id: 'uploads', title: 'Upload & Field Reporting', icon: ClipboardCopy },
  { id: 'ai', title: 'AI Features', icon: Bot },
  { id: 'gis', title: 'GIS & Location Features', icon: Map },
  { id: 'reports', title: 'Reports & Dashboard', icon: PieChart },
  { id: 'activity', title: 'Admin Activity Logs', icon: Activity },
  { id: 'drive', title: 'Google Drive Document Ownership', icon: Folder },
  { id: 'offline', title: 'Offline/PWA Usage', icon: WifiOff },
  { id: 'pilot-plan', title: '15-Day Pilot Plan', icon: FileText },
  { id: 'problems', title: 'Common Problems & Fixes', icon: AlertTriangle },
  { id: 'checklists', title: 'Quick Checklist', icon: CheckSquare },
  { id: 'faq', title: 'FAQ', icon: HelpCircle },
  { id: 'support', title: 'Pilot Support', icon: ShieldCheck },
];